"""set null on quantity unit key

Revision ID: 5947b7023419
Revises: f4f440521956
Create Date: 2023-02-28 21:10:04.399945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5947b7023419'
down_revision = 'f4f440521956'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchased_products', sa.Column('quantity_unit_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'purchased_products', 'quantity_units', ['quantity_unit_id'], ['id'], ondelete='set null')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'purchased_products', type_='foreignkey')
    op.drop_column('purchased_products', 'quantity_unit_id')
    # ### end Alembic commands ###
