"""add unique prop to type and unit

Revision ID: 9c13e085e5f6
Revises: 5947b7023419
Create Date: 2023-02-28 21:32:30.755715

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9c13e085e5f6"
down_revision = "5947b7023419"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_product_types_type"), "product_types", ["type"], unique=True
    )
    op.create_index(
        op.f("ix_quantity_units_unit"), "quantity_units", ["unit"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_quantity_units_unit"), table_name="quantity_units")
    op.drop_index(op.f("ix_product_types_type"), table_name="product_types")
    # ### end Alembic commands ###
