"""added unique props to stock product id

Revision ID: aef0d1ee3d46
Revises: bfdfb033be0e
Create Date: 2023-04-02 11:40:53.103618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aef0d1ee3d46'
down_revision = 'bfdfb033be0e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_stocks_product_id', table_name='stocks')
    op.create_index(op.f('ix_stocks_product_id'), 'stocks', ['product_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stocks_product_id'), table_name='stocks')
    op.create_index('ix_stocks_product_id', 'stocks', ['product_id'], unique=False)
    # ### end Alembic commands ###
