"""move barcode

Revision ID: f4f440521956
Revises: be22ad15cb7d
Create Date: 2023-02-28 20:28:45.633355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4f440521956'
down_revision = 'be22ad15cb7d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'barcode')
    op.add_column('purchased_products', sa.Column('barcode', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchased_products', 'barcode')
    op.add_column('products', sa.Column('barcode', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
